config/routes.rb
Rails.application.routes.draw do
  resource :user do
    resources :subs, only: [:new, :create, :destroy, :edit, :update]
    resources :posts, only: [:new, :create, :destroy, :edit, :update]
  end

  resource :session, only: [:new, :create, :destroy]

  resources :subs, only: [:show, :index]

  resources :posts, only: [:show]

end

app/models/post.rb
class Post < ActiveRecord::Base

  belongs_to :author,
    class_name: "User"

  has_many :cross_posts,
    foreign_key: :post_id,
    class_name: "PostSub"

  has_many :subs,
    through: :cross_posts,
    source: :post

end

app/models/post_sub.rb
class PostSub <ActiveRecord::Base

  validates :post_id, :sub_id, presence: true

  belongs_to :post

  belongs_to :sub
end

app/models/sub.rb
class Sub < ActiveRecord::Base
  belongs_to :moderator,
    class_name: "User"

  has_many :post_crosses,
    foreign_key: :post_id,
    class_name: "PostSub"

  has_many :posts,
    through: :post_crosses,
    source: :post

  validates :moderator, presence: true
  validates :title, :description, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_reader :password
  validates :email, :password_digest, :session_token, presence: true
  validates :email, :session_token, uniqueness: true
  before_validation :ensure_session_token

  has_many :posts,
    foreign_key: :author_id,
    class_name: "Post", dependent: :destroy

  has_many :subs,
    foreign_key: :moderator_id,
    class_name: "Sub", dependent: :destroy

  def self.find_by_credential(email, password)
    user = User.find_by(email: email)
    if user.is_password?(password)
      user
    else
      nil
    end
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def reset_session_token!
    self.session_token = SecureRandom::urlsafe_base64
    self.save!
  end

  def ensure_session_token
    self.session_token ||= SecureRandom::urlsafe_base64
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def require_user!
    redirect_to new_session_url if current_user.nil?
  end

  def log_in(user)
    user.reset_session_token!
    session[:session_token] = user.session_token
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :require_user!
  before_action :require_author!, only: [:edit, :update, :destroy]

  def show
    @post = Post.find(params[:id])
    render :show
  end

  def new
    @post = Post.new
    render :new
  end

  def create
    @post = current_user.posts.new(post_params)

    if @post.save
      redirect_to post_url(@post)
    else
      flash[:error] = @post.errors.full_messages
      render :new
    end
  end

  def update
    begin
      @post = current_user.posts.update(params[:id], post_params)
      render post_url(@post)
    rescue
      flash[:error] = @post.errors.full_messages
      render :edit
    end

  end

  def edit
    @post = Post.find(params[:id])
    render :edit
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to user_url
  end

  private

  def require_author!
    @post = Post.find(params[:id])
    redirect_to user_url unless current_user.id == @post.author_id
  end

  def post_params
    params.require(:post).permit(:title, :content)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.find_by_credential(params[:user][:email], params[:user][:password])

    if @user
      log_in(@user)
      redirect_to user_url
    else
      render :new
    end
  end

  def destroy
    current_user.reset_session_token!
    session[:session_token] = nil
    redirect_to new_session_url
  end

end

app/controllers/subs_controller.rb
class SubsController < ApplicationController

  before_action :require_user!
  before_action :require_moderator!, only: [:edit, :update, :destroy]

    def index
      render :index
    end

  def show
    @sub = Sub.find(params[:id])
    render :show
  end

  def new
    @sub = Sub.new
    render :new
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.moderator = current_user

    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash[:error] = @sub.errors.full_messages
      render :new
    end
  end

  def update

  end

  def edit
    @sub = Sub.find(params[:id])
    render :edit
  end

  def destroy
    @sub = Sub.find(params[:id])
    @sub.destroy
    redirect_to subs_url
  end

  private

  def require_moderator!
    @sub = Sub.find(params[:id])
    redirect_to subs_url unless current_user.id == @sub.moderator_id
  end

  def sub_params
    params.require(:sub).permit(:title, :description)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      log_in(@user)
      redirect_to user_url
    else
      render :new
    end
  end

  def show
    @user = current_user
    render :show
  end

  def edit
    @user = current_user
    render :edit
  end

  def update
    @user = User.new(user_params)
    if @user.save
      redirect_to user_url
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def auth_token
      html = <<-HTML
      <input
       type="hidden"
       name="authenticity_token"
       value="#{form_authenticity_token}">
     HTML
     html.html_safe
  end

  def logged_in?
    !!current_user
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/sub_helper.rb
module SubHelper
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RDClone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<h1>
  <% if logged_in? %>
  <%= current_user.email %>
  <%= button_to "log_out", session_url, method: :delete %>
  <% end %>
</h1>

<body>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<% action_url = post.persisted? ? user_post_url(post) : user_posts_url %>
<% action = post.persisted? ? "PATCH" : "POST" %>

<form action= <%= action_url %> method="post">
    <%= auth_token %>
  <input type="hidden" name="_method" value=<%= action %> >
  <input type="text" name="post[title]" value="">
  <textarea name="post[content]" rows="8" cols="40"><%= post.content %></textarea>
  <input type="submit" value="Submit">
</form>

app/views/posts/new.html.erb
<%= render 'form', post: @post %>

app/views/posts/show.html.erb
HI,BOB

app/views/subs/_form.html.erb
<% action_url = sub.persisted? ? user_sub_url(sub) : user_subs_url %>
<% action = sub.persisted? ? "PATCH" : "POST" %>

<form action= <%= action_url %> method="post">
<%= auth_token %>

  <input type="hidden" name="_method" value= <%= action %>>

  <label> Title
    <input type="text" name="sub[title]" value= <%= sub.title %>>
  </label>

  <label> description
    <textarea name="sub[description]" rows="8" cols="40"><%= sub.description %></textarea>
  </label>

  <input type="submit" value="submit">
</form>

app/views/subs/edit.html.erb
<p>
  Edit Sub
</p>

<%= render 'form', sub: @sub %>

app/views/subs/index.html.erb
Poasdfwe

app/views/subs/new.html.erb
<%= render "form", sub: @sub %>

app/views/subs/show.html.erb
Hi cats


<%= button_to "Edit", edit_user_sub_url(@sub), method: :get %>
<%= button_to "Delete Sub", user_sub_url(@sub), method: :delete %>

app/views/users/_form.html.erb
<% action_url = user.persisted? ? user_url : user_url %>
<% action = user.persisted? ? 'PATCH' : 'POST' %>



<form action="<%= action_url %>" method="post">
  <%= auth_token %>
  <input type="hidden" name="_method" value="<%= action %>">
<label >
  Email:
  <input type="text" name="user[email]" value="<%= @user.email %>">
</label>
<label>
  Password:
  <input type="password" name="user[password]">
</label>
  <input type="submit" value="Submit">
</form>

app/views/users/edit.html.erb
Edit
<%= render "form", user: @user %>

app/views/users/new.html.erb
Sign Up
<%= render 'form', user: @user %>

app/views/users/show.html.erb
<% @user.attributes.each do |_, attribute| %>
  <%= attribute %>
<% end %>



<label>
  Subs
<% @user.subs.each do |sub|%>
  <label>
  <%= link_to sub.title, sub_url(sub) %>
  </label>
  <br>
  <label>
  <%= sub.description %>
  </label>
 <br>
<% end %>
</label>

<br>
<label>
  Posts
<% @user.posts.each do |post|%>
  <label>
  <%= link_to post.title, post_url(post) %>
  </label>
  <br>
  <label>
  <%= post.content %>
  </label>
  <br>
<% end %>
</label>